#!/bin/bash
#
#  Command Line Interface to start all services associated with the Getting-Started Tutorial
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#

docker exec db-mysql /usr/bin/mysqldump -u root --password=secret idm >backup.sql



